# Generated by Django 4.2.1 on 2025-06-23 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', utils.models.SnowflakeIDField(primary_key=True, serialize=False)),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, help_text='内容', null=True, verbose_name='内容')),
                ('category', models.CharField(blank=True, help_text='分类', max_length=50, null=True, verbose_name='分类')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', help_text='状态（0正常 1停用）', max_length=1, verbose_name='状态（0正常 1停用）')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '系统-示例表',
                'verbose_name_plural': '系统-示例表',
                'db_table': 'sys_example',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
