# Generated by Django 4.2.1 on 2024-01-13 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_dept', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='dept',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='上级部门', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_dept.dept', verbose_name='上级部门'),
        ),
        migrations.AlterUniqueTogether(
            name='dept',
            unique_together={('dept_name', 'dept_key')},
        ),
    ]
